aliases:
  jvm_docker: &jvm_docker
    docker:
      - image: circleci/openjdk:11.0.2-jdk

  jvm_options: &jvm_options
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

  working_dir: &working_dir
    working_directory: ~/repo

  jvm_default: &jvm_default
    <<: *jvm_docker
    <<: *jvm_options
    <<: *working_dir

version: 2
jobs:
  build:
    <<: *jvm_default

    steps:
      - restore_cache:
          keys:
            - v3-source-{{ .Branch }}-{{ .Revision }}
            - v3-source-{{ .Branch }}-
            - v3-source-
      - checkout
      - save_cache:
          key: v3-source-{{ .Branch }}-{{ .Revision }}
          paths: ".git"

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "build.gradle" }}
            - v3-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v3-dependencies-{{ checksum "build.gradle" }}

      - restore_cache:
          keys:
            - v3-build-{{ .Branch }}-{{ .Revision }}
            - v3-build-{{ .Branch }}-
            - v3-build-
      - run: gradle build
      - save_cache:
          paths:
            - .gradle
            - build
          key: v3-build-{{ .Branch }}-{{ .Revision }}

  fatJar:
    <<: *jvm_default

    steps:
      - restore_cache:
          keys:
            - v3-source-{{ .Branch }}-{{ .Revision }}
            - v3-source-{{ .Branch }}-
            - v3-source-
      - checkout
      - save_cache:
          key: v3-source-{{ .Branch }}-{{ .Revision }}
          paths: ".git"

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "build.gradle" }}
            - v3-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v3-dependencies-{{ checksum "build.gradle" }}

      - restore_cache:
          keys:
            - v3-build-{{ .Branch }}-{{ .Revision }}
            - v3-build-{{ .Branch }}-
            - v3-build-
      - run: gradle build
      - save_cache:
          paths:
            - .gradle
            - build
          key: v3-build-{{ .Branch }}-{{ .Revision }}

      - run:
          name: Build fat jar
          command: gradle fatJar

      - persist_to_workspace:
          root: build/libs
          paths: assessor.jar

  reports-generate:
    <<: *jvm_default

    steps:
      - restore_cache:
          keys:
            - v3-source-{{ .Branch }}-{{ .Revision }}
            - v3-source-{{ .Branch }}-
            - v3-source-
      - checkout
      - save_cache:
          key: v3-source-{{ .Branch }}-{{ .Revision }}
          paths: ".git"

      - attach_workspace:
          at: workspace
      - run:
          name: Build reports
          command: |
            java -jar workspace/assessor.jar all --long --dir workspace/reports
            java -jar workspace/assessor.jar all --json --dir workspace/reports/json
      - run:
          name: Generate index.md
          command: |
            REPORTS_DIR=workspace/reports
            shopt -s nullglob
            REPORTS=($REPORTS_DIR/*.txt)
            IFS=$'\n'
            REPORTS=($(sort -n -r -t $'-' -k 1 <<<"${REPORTS[*]}"))

            INDEX_FILE=$REPORTS_DIR/index.md
            touch $INDEX_FILE

            echo "Reports: ${REPORTS[*]}"
            echo "# Assessor's Archive" >> $INDEX_FILE
            echo "" >> $INDEX_FILE
            echo "[Latest Assessment]($(basename "${REPORTS[0]}"))" >> $INDEX_FILE
            echo "" >> $INDEX_FILE
            echo "List of assessments:" >> $INDEX_FILE
            echo "" >> $INDEX_FILE
            for report in "${REPORTS[@]}"; do
              REPORT_FILENAME=$(basename "$report")
              echo "* [$REPORT_FILENAME]($REPORT_FILENAME)" >> $INDEX_FILE;
            done;
      - persist_to_workspace:
          root: workspace
          paths: reports
      - store_artifacts:
          path: workspace/reports
          destination: reports

  reports-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - restore_cache:
          keys:
            - v3-source-{{ .Branch }}-{{ .Revision }}
            - v3-source-{{ .Branch }}-
            - v3-source-
      - checkout
      - save_cache:
          key: v3-source-{{ .Branch }}-{{ .Revision }}
          paths: ".git"

      - attach_workspace:
          at: workspace
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@agoranomic.org"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "1b:a0:f8:4f:da:a0:be:ce:6c:08:ca:a1:d9:73:0d:ad"
      - run:
          name: Copy reports to gh-pages dir
          command: cp -R workspace/reports/* generation/gh-pages
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] CI Updates" --dist generation/gh-pages

workflows:
  version: 2
  build_and_report:
    jobs:
      - build
      - fatJar:
          requires:
            - build
      - reports-generate:
          requires:
            - fatJar
      - reports-deploy:
          requires:
            - reports-generate
          filters:
            branches:
              only: master