executors:
  jvm_default:
    docker:
      - image: circleci/openjdk:11.0.2-jdk
    environment:
      TERM: dumb
    working_directory: ~/repo

commands:
  checkout_cached:
    description: "Checkout the repo, using a cache for the .git directory"
    steps:
      - restore_cache:
          name: Restore git cache
          keys:
            - v5-source-{{ .Branch }}-{{ .Revision }}
            - v5-source-{{ .Branch }}-
            - v5-source-
      - checkout
      - save_cache:
          name: Save git cache
          key: v5-source-{{ .Branch }}-{{ .Revision }}
          paths: ".git"
  dependencies_cached:
    description: "Download gradle dependencies, using a cache"
    steps:
      - restore_cache:
          name: Restore dependency cache
          keys:
            - v5-dependencies-{{ checksum "build.gradle.kts" }}
            - v5-dependencies-
      - run: gradle dependencies
      - save_cache:
          name: Save dependency cache
          paths:
            - ~/.gradle
          key: v5-dependencies-{{ checksum "build.gradle.kts" }}
  build_cached:
    description: "Run the gradle build, using a cache"
    steps:
      - restore_cache:
          name: Restore build cache
          keys:
            - v5-build-{{ .Branch }}-{{ .Revision }}
            - v5-build-{{ .Branch }}-
            - v5-build-
      - run: gradle build
      - save_cache:
          name: Save build cache
          paths:
            - .gradle
            - build
          key: v5-build-{{ .Branch }}-{{ .Revision }}
  checkout_and_build:
    description: "Checkout the repository, then build it"
    steps:
      - checkout_cached
      - dependencies_cached
      - build_cached

version: 2.1
jobs:
  build:
    executor: jvm_default
    steps:
      - checkout_and_build
      - store_test_results:
          path: build/test-results/test

  fat-jar-generate:
    executor: jvm_default
    steps:
      - checkout_and_build
      - run:
          name: Build fat jar
          command: gradle fatJar

      - persist_to_workspace:
          root: build/libs
          paths: assessor.jar

  reports-generate:
    executor: jvm_default
    steps:
      - checkout_cached
      - attach_workspace:
          at: workspace
      - run:
          name: Build reports
          command: |
            java -jar workspace/assessor.jar all --long --dir workspace/reports
            java -jar workspace/assessor.jar all --json --dir workspace/reports/json
      - run:
          name: Generate index.md
          command: |
            REPORTS_DIR=workspace/reports
            shopt -s nullglob
            REPORTS=($REPORTS_DIR/*.txt)
            IFS=$'\n'
            REPORTS=($(sort -n -r -t $'-' -k 1 \<<<"${REPORTS[*]}"))

            INDEX_FILE=$REPORTS_DIR/index.md
            touch $INDEX_FILE

            echo "Reports: ${REPORTS[*]}"
            echo "# Assessor's Archive" >> $INDEX_FILE
            echo "" >> $INDEX_FILE
            echo "[Latest Assessment]($(basename "${REPORTS[0]}"))" >> $INDEX_FILE
            echo "" >> $INDEX_FILE
            echo "List of assessments:" >> $INDEX_FILE
            echo "" >> $INDEX_FILE
            for report in "${REPORTS[@]}"; do
              REPORT_FILENAME=$(basename "$report")
              echo "* [$REPORT_FILENAME]($REPORT_FILENAME)" >> $INDEX_FILE;
            done;
      - persist_to_workspace:
          root: workspace
          paths: reports
      - store_artifacts:
          path: workspace/reports
          destination: reports

  reports-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout_cached
      - attach_workspace:
          at: workspace
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@agoranomic.org"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "1b:a0:f8:4f:da:a0:be:ce:6c:08:ca:a1:d9:73:0d:ad"
      - run:
          name: Copy reports to gh-pages dir
          command: cp -R workspace/reports/* generation/gh-pages
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] CI Updates" --dist generation/gh-pages

workflows:
  version: 2
  build_and_report:
    jobs:
      - build
      - fat-jar-generate:
          requires:
            - build
      - reports-generate:
          requires:
            - fat-jar-generate
      - reports-deploy:
          requires:
            - reports-generate
          filters:
            branches:
              only: master
