package org.agoranomic.assessor.decisions

import org.agoranomic.assessor.lib.Player

val Alexis = Player("Alexis")
val Aris = Player("Aris")
val ATMunn = Player("ATMunn")
val Bernie = Player("Bernie")
val Rance = Player("Rance")
val BaronVV = Player("Baron von Vanderham")
val Corona = Player("Corona")
val CuddleBeam = Player("Cuddle Beam")
val DMargaux = Player("D. Margaux")
val Falsifian = Player("Falsifian")
val G = Player("G.")
val Gaelan = Player("Gaelan")
val Halian = Player("Halian")
val JacobArduino = Player("Jacob Arduino")
val Jason = Player("Jason")
val L = Player("L")
val Murphy = Player("Murphy")
val nch = Player("nch")
val o = Player("o")
val Oerjan = Player("Oerjan") // Not a player, just a watcher
val omd = Player("omd")
val pikhq = Player("pikhq")
val PSS = Player("Publius Scribonius Scholasticus")
val RLee = Player("R. Lee")
val Tarhulindur = Player("Tarhulindur")
val Telnaior = Player("Telnaior")
val Trigon = Player("Trigon")
val twg = Player("twg")
val Walker = Player("Walker")
