package org.agoranomic.assessor.decisions

import org.agoranomic.assessor.lib.Person

val ais523 = Person("ais523")
val Alexis = Person("Alexis")
val Aris = Person("Aris")
val ATMunn = Person("ATMunn")
val Bernie = Person("Bernie")
val Rance = Person("Rance")
val BaronVV = Person("Baron von Vanderham")
val Corona = Person("Corona")
val CuddleBeam = Person("Cuddle Beam")
val DMargaux = Person("D. Margaux")
val Falsifian = Person("Falsifian")
val G = Person("G.")
val Gaelan = Person("Gaelan")
val grok = Person("grok")
val Halian = Person("Halian")
val JacobArduino = Person("Jacob Arduino")
val Jason = Person("Jason")
val L = Person("L")
val Murphy = Person("Murphy")
val nix = Person("nix")
val o = Person("o")
val Oerjan = Person("Oerjan") // Not a player, just a watcher
val omd = Person("omd")
val pikhq = Person("pikhq")
val PSS = Person("Publius Scribonius Scholasticus")
val RLee = Person("R. Lee")
val sukil = Person("sukil")
val Tarhulindur = Person("Tarhulindur")
val Tcbapo = Person("Tcbapo")
val Telnaior = Person("Telnaior")
val Trigon = Person("Trigon")
val twg = Person("twg")
val Walker = Person("Walker")
val Warrigal = Person("Warrigal")
