name: CI

on:
  push:
    branches-ignore: gh-pages
  pull_request:
    branches-ignore: gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble --no-daemon --no-watch-fs
      - name: Run the tests
        run: ./gradlew check --no-daemon --no-watch-fs

      - name: Build application distribution
        run: ./gradlew installDist --no-daemon --no-watch-fs

      - name: Upload application distribution
        uses: actions/upload-artifact@v3
        with:
          name: assessor_dist
          path: build/install/assessor

  reports_generate:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17

      - name: Fetch distribution
        uses: actions/download-artifact@v3
        with:
          name: assessor_dist
          path: dist

      - name: Generate reports
        run: |
          chmod +x dist/bin/assessor
          dist/bin/assessor all --long --dir reports
          dist/bin/assessor all --json --dir reports/json
          dist/bin/assessor all --proposals --dir reports/proposal

      - name: Generate index.md
        run: |
          REPORTS_DIR=reports
          shopt -s nullglob
          REPORTS=("$REPORTS_DIR"/*.txt)
          IFS=$'\n' REPORTS=($(sort -n -r -t $'-' -k 1 <<<"${REPORTS[*]}"))
          unset IFS

          LATEST_REPORT_DEST="$REPORTS_DIR/latest.txt"
          INDEX_FILE="$REPORTS_DIR/index.md"
          touch $INDEX_FILE

          echo "Reports: ${REPORTS[*]}"
          echo "# Assessor's Archive" >> $INDEX_FILE
          echo "" >> $INDEX_FILE
          echo "[Latest Assessment]($(basename "${REPORTS[0]}"))" >> $INDEX_FILE
          echo "" >> $INDEX_FILE
          echo "List of assessments:" >> $INDEX_FILE
          echo "" >> $INDEX_FILE
          for report in "${REPORTS[@]}"; do
            REPORT_FILENAME=$(basename "$report")
            echo "* [$REPORT_FILENAME]($REPORT_FILENAME)" >> $INDEX_FILE;
          done;

          cp -- "${REPORTS[0]}" "$LATEST_REPORT_DEST"

      - name: Upload reports artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports

  reports_deploy:
    if: github.ref == 'refs/heads/main'
    needs: reports_generate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
      
      - name: Fetch reports artifact
        uses: actions/download-artifact@v3
        with:
          name: reports
          path: artifacts/reports

      - name: Copy reports to gh-pages dir
        run: "cp -R artifacts/reports/* generation/gh-pages"

      - name: Deploy reports to Github Pages
        uses: crazy-max/ghaction-github-pages@v2.0.0
        with:
          target_branch: gh-pages
          keep_history: true
          allow_empty_commit: false
          build_dir: "generation/gh-pages"
          author: "ci-build <ci-build@agoranomic.org>"
          commit_message: "[skip ci] CI Updates"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
